sonar.projectKey=LucasZampronio_poa-transparente
sonar.organization=lucaszampronio
sonar.host.url=https://sonarcloud.io

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=api/src,web/src,etl
sonar.tests=test
sonar.test.inclusions=test/**/*.test.ts

# Encodings
sonar.sourceEncoding=UTF-8

# Coverage Report
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Exclusions
sonar.exclusions=**/node_modules/**,**/dist/**,**/__pycache__/**
